CREATE TABLE KUSER (
    Firstname VARCHAR(50) NOT NULL,
    Lastname VARCHAR(50) NOT NULL,
	Phone VARCHAR(10) NOT NULL,
	Addr VARCHAR(255) NOT NULL,
	Active BOOLEAN DEFAULT TRUE NOT NULL,
    PRIMARY KEY (Phone)
);
